### PR TITLE
feat: add new script to collect non-ready node

### PR DESCRIPTION
**Pull request by Yu-Jack**
https://github.com/harvester/docs/pull/696

### CODE REVIEW

**Comment by bk201** [comment]
I'll suggest re-using this script: https://github.com/rancher/support-bundle-kit/blob/master/hack/collector-harvester
The script should run well with some correct arguments.

If we create another new script, we'll need to take care of two places in the future. Also the script should be added to the OS image too.

**Comment by Yu-Jack** [comment]
If you'd like users to execute the script to collect data, I think keeping less steps is more simple for them. Otherwise, users still need to execute `mkdir` to create folder by themselves, or execute `source` to make sure the environment variable like my original PR.

**Comment by Yu-Jack** [comment]
Okay, I know how to do. Just use `support-bundle-collector.sh` with specific args.

**Comment by Yu-Jack** [comment]
Okay, I use another way to execute it.

**Comment by Yu-Jack** [comment]
BTW, this script can be executed in v1.2, v1.3 and v1.4.

**Comment by bk201** [comment]
@Yu-Jack Thanks! Do we really need to create the script, or can we just put the entire script in the doc?

**Pull request closed without merging**
