### PR TITLE
fix(agent-daemonset): tolerate all taints

### PR DESCRIPTION
**Pull request by c3y1huang**
Propose to have Agent DaemonSet respecting all taints to avoid getting blocked in node bundle collection. Because in Longhorn, we cannot predict and have no control over the node taints.

https://github.com/longhorn/longhorn/issues/2759

### CODE REVIEW

**Review by innobead — APPROVED** [review]
LGTM.

This can be improved in the future if we really need to respect nodes with customized taints instead of hard-code here.

**Comment by ibrokethecloud** [comment]
Is the aim of the change to allow the support-bundle-kit ds to be deployed to nodes with user taints?

currently the sbk, will wait for zip files to be available from nodes, which match the following criteria:

https://github.com/rancher/support-bundle-kit/blob/master/pkg/manager/manager.go#L332

Any nodes not meeting the criteria will not be included in the map, and sbk will not wait for the corresponding zip files to be available.

**Comment by c3y1huang** [comment]
Do you mean we should ask the user to add labels and pick out the untainted nodes?

**Comment by innobead** [comment]
> Is the aim of the change to allow the support-bundle-kit ds to be deployed to nodes with user taints?
> 
> 
> 
> currently the sbk, will wait for zip files to be available from nodes, which match the following criteria:
> 
> 
> 
> https://github.com/rancher/support-bundle-kit/blob/master/pkg/manager/manager.go#L332
> 
> 
> 
> Any nodes not meeting the criteria will not be included in the map, and sbk will not wait for the corresponding zip files to be available.

Does this criteria respect user taints? It seems only respecting node selector, so tainted nodes will still be counted into the map?

**Comment by bk201** [comment]
> LGTM.
> 
> This can be improved in the future if we really need to respect nodes with customized taints instead of hard-code here.

LGTM, adding an issue to track: https://github.com/rancher/support-bundle-kit/issues/57

**Review by bk201 — APPROVED** [review]

**Review by ibrokethecloud — APPROVED** [review]
LGTM.

 Just verified and in maintenance modes the kubelet is ready, which should still allow the manager to collect node bundles from these nodes.

**Pull request merged**
