### PR TITLE
build: fix wrong dockerfile configuration for multi-platform

### PR DESCRIPTION
**Pull request by yangchiu**
build: fix wrong dockerfile configuration for multi-platform

Signed-off-by: Yang Chiu <yang.chiu@suse.com>

### CODE REVIEW

**Review by innobead — APPROVED** [review]
LGTM. Waiting for @yangchiu test result before merging. 

The publish pipeline in the drone job does not rebuild the binary based on the different arch, but rather just uses the built binary from the previous build pipeline. 

ref: https://github.com/rancher/support-bundle-kit/blob/master/package/Dockerfile#L20-L27

**Comment by yangchiu** [comment]
Since no access to the drone server to evaluate the built image, and it's difficult to tell if it's built correctly from the drone log, I can only test it by executing `dapper ci` on a random `arm64` machine:

```
# dapper ci
# docker run -it --entrypoint /bin/sh rancher/support-bundle-kit:dev
sh-4.4# file /usr/bin/tini
/usr/bin/tini: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=a6090e14afd1fea9a646fe4a0bd090f2fc041e85, stripped
```

I think we can give it a try.

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@yangchiu you can verify the master head image first after merging.

**Review by bk201 — APPROVED** [review]
LGTM

**Comment by yangchiu** [comment]
```
# docker run -it --entrypoint /bin/sh rancher/support-bundle-kit:master-head
sh-4.4# file /usr/bin/tini
/usr/bin/tini: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=a6090e14afd1fea9a646fe4a0bd090f2fc041e85, stripped
```
@c3y1huang can check if it works for longhorn.

**Comment by c3y1huang** [comment]
> @c3y1huang can check if it works for longhorn.

Verified, ref: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2597/.

**Comment by yangchiu** [comment]
> > @c3y1huang can check if it works for longhorn.
> 
> Verified, ref: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2597/.

Yes! Shall we tag a new version? Or temporarily use master-head for testing?

**Comment by c3y1huang** [comment]
> Yes! Shall we tag a new version? Or temporarily use master-head for testing?

We need to tag a new version. /cc @bk201

**Pull request merged**
